name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Create the 'dist' directory to avoid issues with missing directory
      - name: Create dist directory
        run: mkdir -p dist

      # Run the snake animation generator for light mode
      - uses: Platane/snk@v3
        id: snake-gif-light
        with:
          github_user_name: rohitdash08

      # Move the generated SVG to the 'dist' folder for light mode
      - name: Move snake gif to dist (light mode)
        run: |
          mv ./github-contribution-grid-snake.svg dist/github-contribution-grid-snake.svg || echo "Light mode SVG not found."

      # Run the snake animation generator for dark mode
      - uses: Platane/snk@v3
        id: snake-gif-dark
        with:
          github_user_name: rohitdash08

      # Move the generated SVG to the 'dist' folder for dark mode
      - name: Move snake gif to dist (dark mode)
        run: |
          mv ./github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg || echo "Dark mode SVG not found."

      # Debug step to ensure 'dist' directory and snake files exist
      - name: List dist directory contents
        run: ls -la dist

      # Deploy the snake svgs to the output branch using GitHub Pages action
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_ANIMATION_TOKEN }}
